### PR TITLE
API for Ethcode

### PR DESCRIPTION
**Pull request by Krish-bhardwaj**
### Basic api for Ethcode is ready 
these api end points are compatible with [ethers js ](https://docs.ethers.org/v5/api/) only .
### Make following configuration in test extension 
1. add `extensionDependencies` in your `package.json` file of your extension
```json
  "extensionDependencies": [
    "7finney.ethcode"
  ],
```
2. Get the extension's api object 
	``` javascript
	let ethcodeExtension: any = vscode.extensions.getExtension('7finney.ethcode');
	let api = ethcodeExtension.exports;
	```
### Currently available api endpoints are 
1. To check status wethere the api is working or not 
	```javascript
	const data = api.status() // returns "ok" if it is working 
	```
2. **Wallet related API endpoints**
2.1. get wallet component
	```javascript
	const wallet = await api.wallet.get(account) 
	// return object of Wallet class ( Signer ) to the account that is selected 
	```
	this will return [wallet](https://docs.ethers.org/v5/api/signer/#Wallet) component of ethers js 
      2.2. List all wallet present in ethcode
	```javascript
	const listOfWallets = await api.wallet.list()
	// return array of wallets in ethcode
	```

3. **Provider related API endpoints**
	3.1.  get provider component
	```javascript
	const provider = api.provider.get()
	// return provider object
	```
	this will return [provider](https://docs.ethers.org/v5/api/providers/) component of ethers js 
	3.2. **Network related API endpoints**
			3.2.1. get current network
	```javascript
	const  getCurrentNetwork  =  api.provider.network.get()
	// return object having network configuration 
	// object { 
	//	rpc:"" ,
	//	blockScanner:"",
	//	chainID:"",
	//	nativeCurrency:{
	//	     name:"",
	//	     symbol:"",
	//	     decimals:""
	//	}
	//  }
						 
	```
	3.2.2. set current network
	```javascript
	const  setNetwork  =  api.provider.network.set(networkName)
	// sets the network in ethcode context
	```
	3.2.3. set current network
	```javascript
	const  listNetwork  =  api.provider.network.list()
	// return array of network names in ethcode
	```
4. **Contract related API endpoints**
	4.1. create a contract object 
	```javascript
	let  contract  =  await  api.contract.get(contractAddress,abi,wallet);
	// return contract object 
	```	 
	this will return [contract](https://docs.ethers.org/v5/api/contract/) component of ethers js
	4.2. list functions in contract 
	```javascript
	const  listFunction  =  api.contract.list(abi)
	// return array of function names in contract 
	```	 
	4.3. execute functions of contract 
	```javascript
	let  result  =  await  api.contract.execute(contract_object,  function_name , array_of_param);
	// return result of the execution 
	```

### CODE REVIEW

**Comment by Aniket6990** [comment]
few more API endpoints need to be created.
**1. endpoint for contract abi**
whenever a developer wants to call a specific function of a selected contract from the contract he needs abi but currently the abi is not supplied from the API. 
image
**2. endpoint for deployed JSON address file.**
deployed contract address of selected contract should also be exported from the ETHcode environment in order to call the contract methods.
image

**Comment by Aniket6990** [comment]
This Provider api is incompatible with Web3.js projects.
we are able to use web3.js provider in ethers.js projects but are facing challenges while implementing ethers.js provider in web3.js project
for e.g:
this web3.js provider is working fine with ethers.js
image
this ethers.js provider is not working with web3.js
image

**Comment by Krish-bhardwaj** [comment]
We can use ethers js provider in web 3 js using the `Eip1193Bridge` provided by `@ethersproject/experimental` as shown below 
image
To make required advancements in the API i have 2 options 
1. Is to pass a parameter while making provider to return appropriate provider
2. return by default `Eip1193` provider by default

**Comment by 0mkara** [comment]
Let's not provide more layers of abstraction on this. I think if we just point out the appropriate documentation, `dExt` developers would find it out themselves. I.e use `Eip1193` bridge themselves to make it `Web3Js` compatiable provider.

@Aniket6990 @Krish-bhardwaj

**Pull request merged**
